services:
  worker:
    build:
      context: ./worker
    image: europe-west9-docker.pkg.dev/geometric-flux-421107/voting-images/worker
    platform: linux/amd64
    depends_on:
      - redis
      - db
    networks:
      - back-tier
  vote1:
    build:
      context: ./vote
    image: europe-west9-docker.pkg.dev/geometric-flux-421107/voting-images/vote
    platform: linux/amd64
    depends_on:
      - redis
    networks:
      - back-tier
      - front-tier
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
  vote2:
    build:
      context: ./vote
    platform: linux/amd64
    depends_on:
      - redis
    networks:
      - back-tier
      - front-tier
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
  vote3:
    build:
      context: ./vote
    platform: linux/amd64
    depends_on:
      - redis
    networks:
      - back-tier
      - front-tier
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
  vote4:
    build:
      context: ./vote
    platform: linux/amd64
    depends_on:
      - redis
    networks:
      - back-tier
      - front-tier
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
  result:
    build:
      context: ./result
    platform: linux/amd64
    image: europe-west9-docker.pkg.dev/geometric-flux-421107/voting-images/result
    ports:
      - 4000:4000
    depends_on:
      - db
    networks:
      - back-tier
      - front-tier
  nginx:
    build:
      context: ./nginx
    platform: linux/amd64
    depends_on:
      - vote1
      - vote2
      - vote3
      - vote4
    ports:
      - 8000:8000
    networks:
      - front-tier
  seed:
    image: europe-west9-docker.pkg.dev/geometric-flux-421107/voting-images/seed
    platform: linux/amd64
    depends_on:
      - nginx
    build:
      context: ./seed-data
    networks:
      - front-tier
  redis:
    image: "redis:alpine"
    platform: linux/amd64
    networks:
      - back-tier
    volumes:
        - ./healthchecks/redis.sh:/healthchecks/redis.sh
    healthcheck:
      test: ["CMD", "/healthchecks/redis.sh"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
      start_interval: 5s
  db:
    image: "postgres:15-alpine"
    platform: linux/amd64
    environment:
      POSTGRES_PASSWORD: "postgres"
    networks:
      - back-tier
    volumes:
        - ./healthchecks/postgres.sh:/healthchecks/postgres.sh
    healthcheck:
      test: ["CMD", "/healthchecks/postgres.sh"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
      start_interval: 5s
networks:
  front-tier:
  back-tier:
