apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pvc
        - name: init-db
          emptyDir: {}
      containers:
        - image: postgres:15-alpine
          name: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: data
              name: db-data
      initContainers:
        - name: init-db
          image: docker-git-alpine
          command: ["git clone", "https://gitlab.imt-atlantique.fr/login-nuage/healthchecks"]
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: data
              name: init-db
  selector:
    matchLabels:
      app: postgres
