apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  replicas: 1
  template:
    metadata:
      name: result
      labels:
        app: result
    spec:
      containers:
        - image: europe-west9-docker.pkg.dev/geometric-flux-421107/voting-images/result
          name: result
  selector:
    matchLabels:
      app: result
