apiVersion: batch/v1
kind: Job
metadata:
  name: seed
spec:
  template:
    metadata:
      labels:
        app: seed
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: seed
