apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  template:
    metadata:
      name: worker
      labels:
        app: worker
    spec:
      containers:
        - image: europe-west9-docker.pkg.dev/geometric-flux-421107/voting-images/worker
          name: worker
  selector:
    matchLabels:
      app: worker
